#!/usr/bin/env bash
# Displays best bchool" 10 times using a while loop.
# 9th loop displays hi.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
