#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
# 4th iteration displays bad luck
# 8th iteration displays good luck
# best school for all other iterations

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
