#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# 4th iteration bad luck from china
# 9th iteration bad luck from japan
#17th loop iteration bad luck from italy

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
